logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
version = "auto"
included-patches = "custom-video-buffer"
excluded-patches = "always-autorepeat comments custom-branding disable-zoom-haptics hide-captions-button hide-cast-button hide-email-address hide-filter-bar hide-floating-microphone-button hide-info-cards hide-layout-components hide-load-more-button hide-seekbar hide-timestamp hide-video-action-buttons spoof-app-version tablet-mini-player vanced-microg-support wide-searchbar"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
version = "auto"
included-patches = "compact-header"
excluded-patches = "vanced-microg-support"

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
version = "auto"
included-patches = "sim-spoof"

[Reddit]
apkmirror-dlurl = "https://apkmirror.com/apk/redditinc/reddit/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
version = "auto"

[Messenger]
apkmirror-dlurl = "https://apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
version = "auto"

[Twitter]
apkmirror-dlurl = "https://apkmirror.com/apk/twitter-inc/twitter/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
version = "auto"

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/instagram-instagram/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
version = "auto"

[Sync]
apkmirror-dlurl = "https://www.apkmirror.com/apk/red-apps-ltd/sync-for-reddit/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
version = "auto"

[NetGuard]
apkmirror-dlurl = "https://www.apkmirror.com/apk/marcel-bokhorst/netguard-no-root-firewall/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
version = "auto"
included-patches = "remove-broadcasts-restriction"

[Recorder]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-recorder/"
apkmirror-arch = "both"
build-mode = "both"
version = "auto"

[Trakt]
apkmirror-dlurl = "https://www.apkmirror.com/apk/trakt/trakt/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
version = "auto"

[VSCO]
apkmirror-dlurl = "https://www.apkmirror.com/apk/vsco/vsco-cam/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
version = "auto"
